### ISSUE TITLE
Add remarkable-tablet topic

### ISSUE THREAD

**Issue by Eeems** [lschwetlick/rMsync#19]
https://remarkable.guide/devel/github.html#remarkable-tablet-topic

**Comment by lschwetlick** [comment]
Hi, thanks for your comment. I don't know what it means to "add to a topic" or how it should be done? Do I need to add a label or something?

**Comment by Eeems** [comment]
https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/classifying-your-repository-with-topics

**Comment by lschwetlick** [comment]
Thank you! I finally found the correct cogwheel to click :)
