### ISSUE TITLE
empty.rm?

### ISSUE THREAD

**Issue by malcolmsailor** [lschwetlick/rMsync#4]
Hi, I'm hoping to use this script but I'm running into a problem with `empty.rm`. `sync.py` has the path to an `empty.rm` file somewhere on your computer hardcoded. I replaced this with a reference to the `empty.rm` file included at the top level of this repository. This file, however, is too short and will cause the `rm2svg()` function to abort. I can pad the contents of `empty.rm` with 8 spaces to better match the `expected_header_v3` string in this latter function, but the file will nevertheless be too short by 4 bytes and I'm not sure what the remaining contents should be. Is there a more up-to-date version of `empty.rm` somewhere?

Thanks for your help!

**Comment by lschwetlick** [comment]
Oh interesting. It does seem to be just missing white space. I updated the file, so for me now it works. Let me know if it does for you too!

**Comment by malcolmsailor** [comment]
Yes, that works! Thanks :)
